### ISSUE TITLE
Sprint 3 - Database Schema cleanup

### ISSUE THREAD

**Issue by DeltaO3** [DeltaO3/UWAttend---3200_27#103]
The client noted during the demonstration that they want the database not to use numbers to represent what is effectively strings (e.g. use admin,coordinator, facilitator instead of 1 2 3, use true or false instead of 0 and 1 (i disagree here), etc.)

The client also made note of potentially not needing the active column since we can just use dates.

Any changes should be reflected across the repository - change any database functions to reflect this, use a global search to edit all calls to these functions to reflect these changes. Ideally include testdb.py in these changes (for ease of testing), but note that file will eventually be removed from the repo in the final week

**Comment by livvy10** [comment]
Another change we can do here is changing the uwaID field to string rather than number. Because if the number is 00012222, then the database will store it as 12222, and if we are displaying it on the webapp and using it for emails we would need it to be accurate.

Don't know how I missed that haha

**Comment by DeltaO3** [comment]
Very true! will we need to pass "number" (as a string)or if we pass just number (as an int) does it auto string convert for us ?

**Comment by livvy10** [comment]
change uwaid to email which should be unique (for User)
