### ISSUE TITLE
Sprint 3 - Remove entries from database after some period of time

### ISSUE THREAD

**Issue by DeltaO3** [DeltaO3/UWAttend---3200_27#104]
After some period of time (say, 6 months? 1 year? clarify with client), the client requested that data be removed from the database - this likely specifically includes student data for security purposes, but may include others.

**Comment by ozzy1323232** [comment]
UNIT: delete an expired unit
FACILITATOR / COORDINATOR asciotiation delete
STUDENT unit id in any unit row with ID
SESSIONdeleet any with unit id 
ATTENDNANCE delete any record where sessionid == one that got deleetd
