### ISSUE TITLE
Sprint 3 - Send emails to newly created users

### ISSUE THREAD

**Issue by DeltaO3** [DeltaO3/UWAttend---3200_27#108]
Setup a domain for the email
How do we set up password?

Set password?

**Comment by ipr17** [comment]
remember to remove the conditional where it only sends emails to 23159504@student.uwa.edu.au (as obviously this is only good for testing)

**Comment by ipr17** [comment]
TODO: 
- in admin() send an email to new users asking them to create an account. also remove the password field and set a temporary password 
- send an email when forgot password 
- make sure reset password actually sets the correct users password
-

**Comment by ipr17** [comment]
change colours in emails 
fix flash messages 
remove first and last name from admin page 
change header of the reset password page

**Comment by ipr17** [comment]
token thing

**Comment by ipr17** [comment]
add email sending when adding a new facilitator in Delta and James' PR
