### ISSUE TITLE
Sprint 3 - Indication that connection to the server has been lost 

### ISSUE THREAD

**Issue by ipr17** [DeltaO3/UWAttend---3200_27#128]
Add some kind of visual notice that the server is disconnected. Low priority.

**Comment by ozzy1323232** [comment]
I have made a prototype that works, 

- It adds a Javascript function to main.js that will PING the server every 2 seconds 
- adds a /ping/ route which will responds with OK to signify the server running.

I am stuck on what kind of alert we should use, Do we use Alert() javascript or shoudl we use a Flash() alert?
