### ISSUE TITLE
Sprint 1 - Skills and Resources audit

### ISSUE THREAD

**Issue by DeltaO3** [DeltaO3/UWAttend---3200_27#2]
From the CITS3200 site:

> A Skills and Resources Audit. The idea is that, before you dive into the project, the team should undertake an audit of what skills and tools the team needs to successfully carry out the project, and therefore what you need to learn/acquire (and from where).

**Comment by DeltaO3** [comment]
flask, html, css, js, software documentation, project management, user authentication (via flask)

**Comment by Jimbos21** [comment]
Of the listed skills I am not proficient in any except software documentation, and programming in Python.

**Comment by ipr17** [comment]
flask, html, css, javascript, csv handling, user authentication, software documentation, and project management

**Comment by ozzy1323232** [comment]
html, css, database including sql and kql. software design, C#, Python, Basic knowledge of servers
