### ISSUE TITLE
Sprint 2 - Read in spreadsheet

### ISSUE THREAD

**Issue by ipr17** [DeltaO3/UWAttend---3200_27#27]
Write a function (.py) to read a csv and insert into a db

**Comment by Ay1tsMe** [comment]
Feature not fully implemented

**Comment by Ay1tsMe** [comment]
Functionality works. Now just need to implement frontend buttons for the user

**Comment by Ay1tsMe** [comment]
completed: https://github.com/DeltaO3/UWAttend---3200_27/pull/78
