### ISSUE TITLE
Sprint 2 - Export information as csv

### ISSUE THREAD

**Issue by ipr17** [DeltaO3/UWAttend---3200_27#28]
Dump database as csv (option xlsx)

**Comment by DeltaO3** [comment]
Potentially be able to filter the output by different types of data.

**Comment by DeltaO3** [comment]
has this been merged in?

**Comment by Ay1tsMe** [comment]
Yes but issue still isn't finished. Need to add export button on admin page aswell as import button. Once frontend buttons are functional then this issue and https://github.com/DeltaO3/UWAttend---3200_27/issues/27 can be closed

**Comment by DeltaO3** [comment]
Completed by PR #80
