### ISSUE TITLE
Sprint 2 - Functional homepage

### ISSUE THREAD

**Issue by ipr17** [DeltaO3/UWAttend---3200_27#29]
Student sign in suggestions ✓

Class list search bar ✓

Class list sorting (dynamically adding new students to top of table) ✓

Success noise when sign in ??

Undo button when accidentally signed in? - this is already on the student page and can get messy, maybe not?

When you click on a student it takes you to their student page ✓

**Comment by DeltaO3** [comment]
#38 May be related and comlpeted as part of this issue.

**Comment by DeltaO3** [comment]
Another thing: Story 9 : "need to be able to sign a student in with either a student number or name so that if a student forgets their number they can still sign in.", ideally this is done in this issue

**Comment by ipr17** [comment]
I think most of the work that I can do on this will need to happen once the database is set up, but I've gotten started

**Comment by DeltaO3** [comment]
Search functionality for home page -  search for students when we have lots of students

**Comment by DeltaO3** [comment]
Maybe make signed out units display underneath

**Comment by ipr17** [comment]
All students show up in search bar, students that haven't been signed in are green and students that have are red

**Comment by ipr17** [comment]
If a unit does not have consent then shouldn't be prompted
