### ISSUE TITLE
Sprint 2 - Class reallocation

### ISSUE THREAD

**Issue by DeltaO3** [DeltaO3/UWAttend---3200_27#48]
From user stories:
> "As a professor I need to be able to allocate classes to any staff member so when I can’t make it in, I can allocate someone else to register for the classes and take the attendance for me."

How do we want to implement this? Where should this option be in config? etc.
Requires more thought about implementation - actual implementation should just be an update call to the central DB, and placing the option on the frontend.

**Comment by livvy10** [comment]
I'm under the impression we don't actually want this. I don't think facilitators are assigned to a specific class/session, but to a unit.
There should however be a way (ideally) for unit coordinators to update (add or remove) the facilitators for a unit.

Something to verify with Adrian.

**Comment by DeltaO3** [comment]
Wants some kind of special conditional on certain facilitators/labs. Maybe make its own issue?
