### ISSUE TITLE
Sprint 2 - Database functions

### ISSUE THREAD

**Issue by DeltaO3** [DeltaO3/UWAttend---3200_27#49]
Create a python file in the app (database.py ? name up to the assignee), which should store python functions that perform all required database operations: e.g. reading data (user, student, etc), changing / updating data (mainly for attendance), adding data (attendance, classes etc), etc. 

Names of functions should be fairly self explanatory, and likely will want to be passed a python object as an argument. Testing optional but would be beneficial.

Doesn't have to include every feasible function immediately - this issue can also be completed overtime by other issues as we progress, in which case we should close it.

**Comment by ozzy1323232** [comment]
at the moment all you have to do is call 
user(zac, cits200, etc)
db.commit()

is this something you want in a whole other file or can we just leave in routes.py. I sent a screenshot the other day of the code for it.

**Comment by DeltaO3** [comment]
From Adam's discord message:
>And finally, when it comes to adding users, creating sessions and whatever else we need to do in the database, everything should be written in functions within a separate file. Probably utilities.py is the place to put it? That way it's modular. We don't really want to be manually making sql queries that changes the data unless its for testing purposes.

I personally think putting these in like "databases.py" is neater then putting every single non route function into utilities, but that's a minor issue for me
