### ISSUE TITLE
Sprint 2 - Session creation, facilitator assignment, unit creation

### ISSUE THREAD

**Issue by DeltaO3** [DeltaO3/UWAttend---3200_27#51]
>"I want my class list accessible only by the professors who run the unit so no unauthorised staff can modify or access personal information"

In our admin page, we want to be able to add units, sessions, and assign facilitators / professors to different units. Refer to the flow diagrams for how this would work, keep in discussion with group and client as progress is made to ensure it is done correctly.

**Comment by livvy10** [comment]
Just commenting as I'm not entirely sure facilitators are assigned to sessions, but rather units, meaning any facilitator can have access to the units they are authorised to, and can sign people into any session for a given unit. At least, that is the impression I got and so the user flow diagrams are based on this assumption.

**Comment by DeltaO3** [comment]
Great point, edited the issue, thanks!

**Comment by DeltaO3** [comment]
#65 _May_ be completed as part of this issue?
