### ISSUE TITLE
Sprint 2 - Unit Config page

### ISSUE THREAD

**Issue by livvy10** [DeltaO3/UWAttend---3200_27#57]
Look at user flow diagram 2b

Unit configuration (visible to unit coordinators and admin) 
List units (that the unit coordinator has made)
Configure new unit button

Admin (visible to admin)
Add unit coordinator
Remove unit coordinator

**Comment by livvy10** [comment]
To verify with client about how he wants adding/removing a unit coordinator (or adding/removing an admin user??) to be implemented.

**Comment by DeltaO3** [comment]
Is this still up?

**Comment by Jimbos21** [comment]
It might be superseded if we are splitting admin into admin and configure unit.

**Comment by DeltaO3** [comment]
Superseded by new issue
