### ISSUE TITLE
Sprint 3 - Encrypting Database files

### ISSUE THREAD

**Issue by Ay1tsMe** [DeltaO3/UWAttend---3200_27#63]
Local database files need to be encrypted for security reasons. They should not be accessible by a user unless they have encryption keys.

From a bit of research, best practice is to:
- Enable TDE that connects to the database
- Generate and distribute encryption keys to each team member (NOT THROUGH GIT!!!)

**Comment by DeltaO3** [comment]
Is this about security through the hosting service? We dont have local database files anymore.

**Comment by Ay1tsMe** [comment]
`app.db` needs to encrypted. Otherwise anyone who has access to `app.db` can query the data (Main concern is a red hat having access to all records of students). Both on the server and locally when we initialising `app.db`, the code should encrypt the database.
