### ISSUE TITLE
Planning/Design - User flow diagrams

### ISSUE THREAD

**Issue by livvy10** [DeltaO3/UWAttend---3200_27#7]
Annotated diagrams of app pages to demonstrate how the user will use the app in a typical session. Not a requirement for Sprint 1.

**Comment by livvy10** [comment]
I have just completed the draft user flow diagrams. I will email you a word document containing the 13 diagrams soon. 

3 things to note:

1. In Meeting 2b, we were discussing whether the class list could be already formed, as having students individually signed in takes time and seems unnecessary especially if classes are fixed and already known. I have not done this and kept the student sign in. I did this for two reasons. Firstly, to remain closer to the current app -  most attendance roles at schools have already-formed class lists, so the fact this app doesn't makes me think it was an intentional choice. Also, the fact that he is thinking about using barcodes again makes me think the student sign in is intentional and required. Secondly, it will be easier to remove student sign altogether from the design if we decide to (making the home page just the class list - I have put them together as discussed), rather than adding it in.
2. I forgot to include grades, which the app would ideally support. This should be an easy inclusion - I imagine another field/textbox on the student's page.
3. I have done the config menu as a page, rather than a modal as we were discussing. I did this because I wanted the navbar icons to each be pages, however this is super easy to change if we decide we would prefer the config menu as a modal.

Please give feedback by commenting on this issues (by **this Wednesday 7th Aug**, as that is when I will be implementing your feedback to create a second draft for our meeting with Keating on Friday). Please use numbered list of 13 with your comments so I can tell which pic you are talking about.

**Comment by DeltaO3** [comment]
The document looks pretty good to me - just a question: were we going to display the full class list regardless of sign in and have some indicator of who is and isnt signed in ? Or were we going with the more direct translation of what the app currently is.

**Comment by livvy10** [comment]
> The document looks pretty good to me - just a question: were we going to display the full class list regardless of sign in and have some indicator of who is and isnt signed in ? Or were we going with the more direct translation of what the app currently is.

Ahh ok, I think I understand what you're saying. My brain thought our options were either 1. individual sign in which dynamically builds the class list (same as current app), or 2. already formed fixed class list where there are no "sign in capabilities" but rather students are signed in by a tick field or something, more like what roles are like in schools (what I thought we were leaning towards in the meeting, a much more simple approach but I did the first option for reasons as explained in note 1 above).

However I think what you're saying is that in the meeting we were leaning towards a different option, where the class list is already formed but students are still signed in by a facilitator searching their name/scanning barcode. Is this correct?

> 
> Also, potentially create a pull request with the document adding it the the "sprint 1" directory - both for practice of our future workflow and to have it all on one page/ document that can later be downloaded and submitted once approved

Will try that now, thank you!

**Comment by Ay1tsMe** [comment]
Draft 1 complete. Reopen this issue if further discussion is necessary.
